from_owner:
  - dependabot
  - wjervis7

required_labels:
  - dependencies
  - ready

required_labels_mode: one_of

blacklisted_labels: []

apply_labels: []

auto_squash_merge_labels:
  - dependencies
  - ready
