_extends: github-settings

from_owner:
  - dependabot[bot]
  - wjervis7

required_labels:
  - dependencies
  - ready

required_labels_mode: one_of

blacklisted_labels:
  - wip

apply_labels:
  - merge
  