pool:
  name: Default

trigger:
- main

steps:
- task: DockerInstaller@0
  inputs:
    dockerVersion: "24.0.1"

- task: Docker@2
  displayName: Login
  inputs:
    containerRegistry: "ACR Connection"
    command: "login"

- task: CmdLine@2
  displayName: Build and Push Docker Image
  inputs:
    script: |
      docker run --privileged --rm tonistiigi/binfmt --install arm64,amd64
      docker run --privileged --rm tonistiigi/binfmt
      docker buildx create --use
      docker buildx build --platform linux/amd64,linux/arm64 \
          --build-arg NODE_VERSION=$(cat .nvmrc | tr -cd [:digit:].) \
          -t wjervis.azurecr.io/devops-helper:$(build.buildNumber) \
          -t wjervis.azurecr.io/devops-helper:latest \
          --push \
          .