name: Auto approve

on:   
  pull_request:
    types: [opened, reopened, labeled, edited]
  pull_request_review:
    types: [dismissed]
  pull_request_target:

jobs:
  approve:
    runs-on: ubuntu-latest
    if: github.actor == 'dependabot[bot]' || github.actor == github.repository_owner
    permissions:
      pull-requests: write

    steps:
      - uses: hmarr/auto-approve-action@v3
