---
name: Format Code

on:
  pull_request:
    branches: [main]
    
jobs:
  format:
    name: Validate Code Base
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version-file: '.nvmrc'

      - name: Install dependencies
        run: npm ci

      - name: Lint code (and fix issues)
        run: npm run lint:fix

      - name: Format code
        run: npm run format

      - name: Check in changes
        run: |
          git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}
          git commit -am "Automated Formatting changes"
          git push
    