---
name: Bump version

on: 
  push:
    branches: [main,dev]

jobs:
  tag:
    permissions:
      contents: write
      
    name: Bump Tag version
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Bump version and push tag
        id: tag
        uses: mathieudutour/github-tag-action@v6.1
        with:
          github_token: ${{ secrets.TAG_TOKEN }} 
          default_bump: minor
          pre_release_branches: dev

      - name: Create GitHub Release
        uses: ncipollo/release-action@v1
        with:
          tag: ${{ steps.tag.outputs.new_tag }}
          name: Release ${{ steps.tag.outputs.new_tag }}
          body: ${{ steps.tag.outputs.changelog }}
