---
name: Validate Build

on:
  pull_request:
    branches:
      - main
      - dev

permissions:
  contents: write

jobs:
  format:
    name: Format and Lint Code Base
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
        with:
          persist-credentials: false
          fetch-depth: 0

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version-file: '.nvmrc'

      - name: Install dependencies
        run: npm ci

      - name: Lint code (and fix issues)
        run: npm run lint:fix

      - name: Format code
        run: npm run format

      - name: Commit and Push changes
        uses: wjervis7/git-commit-push@v1-beta7
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          commit_message: "Formatted and linted code"

  build:
    name: Validate Code Base
    runs-on: ubuntu-latest
    needs: format

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version-file: '.nvmrc'

      - name: Install dependencies
        run: npm ci
      
      - name: Lint code
        run: npm run lint
      
      - name: Build code
        run: npm run build
      
      - name: Run Unit Tests
        run: npm run test:unit

      - name: Get Code Coverage
        run: npm run test:coverage

      - name: Update CC badges
        run: npm run make-badges
