---
name: Validate Build

on:
  pull_request:
    branches:
      - main
      - master
      - dev

permissions:
  contents: write
  checks: write
  pull-requests: write

jobs:
  format:
    name: Format Code Base
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version-file: ".nvmrc"

      - name: Install dependencies
        run: npm ci

      - name: Format code
        run: npm run format

  lint:
    name: Lint Code Base
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version-file: ".nvmrc"

      - name: Install dependencies
        run: npm ci

      - name: Lint code
        run: npm run lint


  build:
    name: Validate Code Base
    runs-on: ubuntu-latest
    needs: 
      - format
      - lint

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          ref: ${{ github.head_ref }}

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version-file: ".nvmrc"

      - name: Install dependencies
        run: npm ci

      - name: Build code
        run: npm run build

      - name: Run Unit Tests
        run: npm run test:unit

      - name: Get Code Coverage
        run: npm run test:coverage

      - name: Publish Results
        uses: davelosert/vitest-coverage-report-action@v2
        if: always()

      - name: Publish Results Badge
        uses: wjervis7/vitest-badge-action@v0.12-beta
        if: always()
        with:
          result-type: lines
          gist-token: ${{ secrets.GIST_TOKEN }}
          gist-url: https://gist.github.com/wjervis7/8273a53932b38d5ff3a2870c1ca30059
          badge-path: badge-lines.svg
          badge-text: Coverage (Lines)

      - name: Publish Results Badge
        uses: wjervis7/vitest-badge-action@v0.12-beta
        if: always()
        with:
          result-type: statements
          gist-token: ${{ secrets.GIST_TOKEN }}
          gist-url: https://gist.github.com/wjervis7/8273a53932b38d5ff3a2870c1ca30059
          badge-path: badge-statements.svg
          badge-text: Coverage (Statements)

      - name: Publish Results Badge
        uses: wjervis7/vitest-badge-action@v0.12-beta
        if: always()
        with:
          result-type: functions
          gist-token: ${{ secrets.GIST_TOKEN }}
          gist-url: https://gist.github.com/wjervis7/8273a53932b38d5ff3a2870c1ca30059
          badge-path: badge-functions.svg
          badge-text: Coverage (Functions)

      - name: Publish Results Badge
        uses: wjervis7/vitest-badge-action@v0.12-beta
        if: always()
        with:
          result-type: branches
          gist-token: ${{ secrets.GIST_TOKEN }}
          gist-url: https://gist.github.com/wjervis7/8273a53932b38d5ff3a2870c1ca30059
          badge-path: badge-branches.svg
          badge-text: Coverage (Branches)
