---
name: Validate Build

on:
  workflow_dispatch:
  workflow_run:
    workflows: [Format Code]
    types:
      - completed

jobs:
  build:
    name: Validate Code Base
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version-file: '.nvmrc'

      - name: Install dependencies
        run: npm ci
      
      - name: Lint code
        run: npm run lint
      
      - name: Build code
        run: npm run build
      
      - name: Run Unit Tests
        run: npm run test:unit
